### ISSUE TITLE
Maybe a mistake in the 'rr' grammar ?

### ISSUE THREAD

**Issue by mingodad** [GuntherRademacher/rr#8] opened 2021-06-11 06:41 UTC
Trying to implement `rr` grammar with CocoR https://ssw.jku.at/Research/Projects/Coco/ it seems that there is a mistake in the `rr` grammar for the production `item`:
```
Item                  ::= Primary ( '?' | '*' | '+' )*
```
If I understood it correctly it should be:
```
Item                  ::= Primary ( '?' | '*' | '+' )?
```
Because constructs like this are invalid, isn't it ?
```
Item                  ::= Primary ( '?' | '*' | '+' )*?+  //zero or more *?+ after ')'
```
Cheers !

**Comment by GuntherRademacher** [comment] 2021-06-11 11:14
This is as intended. There is no reason to restrict to a single operator. Especially not on syntax level in the Item production - the parenthesized variant would still be allowed. Also, there is no problem at all with the semantics, and RR's grammar transformation will normalize it.

You may be wondering about ambiguities that could arise with some parser generation schemes, but that is a completely different issue.

**Comment by GuntherRademacher** [comment] 2021-06-18 15:51
Closing - works as it is supposed to.

**Closed** 2021-06-18 15:50 UTC
